#© Copyright Nikolai Patrick 2022. All rights reserved.

baseURL = 'http://projects.nikolaipatrick.com/'
languageCode = 'en-us'
title = 'Projects'
theme = 'dark_lake'
copyright= 'thing'
[params]

  googleAnalytics = 'G-3W5F046QEG'

############
# METADATA #
############

  # The email address for the site author/maintainer:
  email = 'nikolaipatricknp@gmail.com'

  # The classification and categories
  classification = 'Personal'
  category = 'Projects'

  # The type of website, is it a blog, a bio, etc.
  medium = 'blog'

  # The target audience for this site:
  target = 'all'

  # Like a movie rating, will the site contain 18+ content, XXX, etc?
  # Use one of the following: general, mature, restricted, adult, 14 years, safe for kids
  rating = 'general' 

[author]
  [author.author]
    name = "Nikolai Patrick"
    locality = "Old Noarlunga"
    region = "South Australia"
    country = "Australia"

[menu]
  [[menu.topnav]]
    name = 'Home'
    title = 'home/landing page'
    url = "/"
    weight = 1
  [[menu.topnav]]
    name = 'Tags'
    title = 'tags page'
    url = "/tags/"  
    weight = 2  
  [[menu.topnav]]
    name = 'All Articles'
    title = 'see list of all articles'
    url = "/projects/"
    weight = 3    
  [[menu.topnav]]
    name = 'GitHub'
    title = 'Go to GitHub Profile'
    url = 'https://github.com/Smartich0ke'   
    pre =  '<span><img class="externalLink" src="/images/arrow-up-right-from-square-solid.svg" alt="" srcset="" height="12px" width="12px"></span>'
    weight = 4 



[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'monokai'
    tabWidth = 4